apiVersion: v1
kind: Pod
metadata:
  name: pod-with-hostpath-volume
spec:
  restartPolicy: Never
  containers:
  - image: ubuntu
    name: ubuntu-container
    volumeMounts:
      - mountPath: /data
        name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /tmp
        type: Directory