apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      environment: production
  template:
    metadata:
      labels:
        app: nginx
        environment: production
    spec:
      containers:
        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "256M"
              cpu: "0.5"
            requests:
              memory: "128M"
              cpu: "0.25"
    