apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeserve
  labels:
    app: kubeserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeserve
  template:
    metadata:
      labels:
        app: kubeserve
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
          - containerPort: 80